"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Rectangle_1 = require("./Rectangle");
var Circle_1 = require("./Circle");
var Shape_1 = require("./Shape");
var myShape = new Shape_1.Shape(10, 20);
console.log(myShape.getInfo());
var myCircle = new Circle_1.Circle(10, 20, 4.5);
console.log(myCircle.getInfo());
var myRectangle = new Rectangle_1.Rectangle(45, 67, 34, 23);
console.log(myRectangle.getInfo());
