/**
 * RB_Pricing_And_Costing_3
 * This is the RB pricing and costing API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PriceLine { 
    sku?: string;
    vendorPartNumber?: string;
    contractTerm?: number;
    contractTermUnit?: string;
    billingTerm?: number;
    billingTermUnit?: string;
    quantity: number;
    unit?: string;
    unitPrice?: number;
    unitCost?: number;
    inCurrencyCode: string;
    outCurrencyCode: string;
    errorCode?: string;
    errorMessage?: string;
}