/**
 * RB_Pricing_And_Costing_3
 * This is the RB pricing and costing API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PriceLine } from './priceLine';

export interface PriceHeader { 
    serviceClientRequestID?: string;
    serviceRequestID?: string;
    companyCode?: string;
    customerBranch?: string;
    customerNumber: string;
    countryCode: string;
    endUserName?: string;
    endUserID?: string;
    bidNumber?: string;
    validFromDate?: string;
    validToDate?: string;
    priceAsOfDatetime?: string;
    isSaveExplainPlan: boolean;
    isSubscription: boolean;
    correlationID?: string;
    hasLineError?: boolean;
    errorCode?: string;
    errorMessage?: string;
    priceLines: Array<PriceLine>;
}